apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: nginx-external-svc
  name: nginx-external-svc
  namespace: default
subsets:
- addresses:
  - ip: 39.156.69.79 #外部服务的ip
  ports:
  - name: http
    port: 80
    protocol: TCP
