apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-external-svc
  name: nginx-external-svc
spec:
  ports:
  - name: http #service端口的名称
    port: 80 #service自己的端口
    protocol: TCP # UDP TCP SCTP 默认时TCP
    targetPort: 80 # 后端应用的端口
  sessionAffinity: None
  type: ClusterIP 