apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01-5gi
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-gitlab
  nfs:
    path: /data/nfs/k8s/gitlab/data
    server: 192.168.160.171
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02-512mi
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-gitlab
  nfs:
    path: /data/nfs/k8s/gitlab/config
    server: 192.168.160.171
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03-1gi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-gitlab
  nfs:
    path: /data/nfs/k8s/gitlab/config
    server: 192.168.160.171
