kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-gitlab
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: nfs-gitlab
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-gitlab
